# Generated by Django 3.2 on 2022-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_area_adress', models.URLField(default='-', max_length=100)),
                ('place_name', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=100)),
                ('place_detail', models.TextField()),
                ('place_adress', models.CharField(max_length=200)),
                ('place_parking', models.CharField(blank=True, max_length=100, null=True)),
                ('place_access', models.CharField(blank=True, max_length=100, null=True)),
                ('place_opening', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('place_url', models.URLField(blank=True, null=True)),
                ('required_time', models.CharField(blank=True, choices=[('1時間', '1時間'), ('2～3時間', '2～3時間'), ('半日', '半日'), ('日中', '日中')], max_length=100, null=True)),
            ],
        ),
    ]
