# Generated by Django 3.2 on 2022-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
