# Generated by Django 3.2 on 2022-09-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0003_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='areas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotplan.area'),
        ),
    ]
