# Generated by Django 3.2 on 2022-09-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0005_alter_place_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='areas',
            field=models.ForeignKey(default='hokkaido', on_delete=django.db.models.deletion.CASCADE, to='spotplan.area'),
        ),
    ]
