# Generated by Django 3.2 on 2022-10-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0005_auto_20221002_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='area',
            new_name='city',
        ),
    ]
