# Generated by Django 3.2 on 2022-09-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0006_alter_place_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='areas',
        ),
    ]
