# Generated by Django 3.2 on 2022-10-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0006_rename_area_city_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='geo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
