# Generated by Django 3.2 on 2022-10-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0007_place_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='geo',
        ),
        migrations.AddField(
            model_name='place',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
