# Generated by Django 3.2 on 2022-11-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotplan', '0012_likeplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbank',
            name='favorite_place',
        ),
        migrations.RemoveField(
            model_name='userbank',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavUser',
        ),
        migrations.DeleteModel(
            name='UserBank',
        ),
    ]
